# Site settings
title: Brooklyn Park Beat
email: sailorfred@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  The Brooklyn Park Beat prints local news about our community.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brooklynparkbeat.com" # the base hostname & protocol for your site
# facebook_username: Malihini-Orchid-Society-1570771156515839
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown

future: true
